### PR TITLE
Fix mobile issues

### LINKED ISSUE #45: Mobile Issues for v1.0-prod
- [x] Add link to the CASC regions in the regional description. https://www.usgs.gov/programs/climate-adaptation-science-centers 

`now they are shown by <a href="https://www.usgs.gov/programs/climate-adaptation-science-centers" target="_blank">Climate Adaptation Science Center</a> regions`

_Originally posted by @aaarcher-usgs in https://github.com/DOI-USGS/drought-timeline/issues/44#issuecomment-1715771716_
            

- [x] Additionally, on mobile, load screen has overlap between buttons and navigation bar on my iPhone and on mocked SE (see screenshot below).

image

- [x] Additionally, on mobile, regional violin is left-aligned rather than centered below map.

image

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
### Changes

Fixes #45 by:
* Adding the reference to the CASC regions
* Centering the violin chart on mobile
* Editing the intro section (text content, text line height, section padding) to condense it on mobile, in hopes of keeping the annotation container and nav button container from overlapping on load

Other changes:
* Edit interaction prompt on mobile to say 'tap' instead of 'click'
* Reduce y-axis x offset on mobile
* Drop droughtText font-sizing on desktop and mobile, so that sizing matches default set for body in `App.vue`. As is they are just slightly different
* Make keys for dynamically added narration content unique to drop duplicate key console warnings
* Fix the button styling on mobile - when 'hovered' it was losing the border. Also edited 'active' styling to match currentButton
* Adjust scroll offset in `scrollTimeline(e)` to a) depend on device type and b) depend on window height, and also tweaked it to better line up w/ scroll Triggers for major droughts, so that a) _first_ narration is in view upon button-triggered scroll, not second, and b) scroll button is active when scrolling finishes.
* Slightly lengthen the window for `currentButton` styling by moving the trigger end up the page - this aligns its deactivation a bit better with when the 2nd drought narration disappears
* Add the `overlayTopMargin` into the viewBox for `svg-dynamic`, so that final y-axis label isn't cut off

### To test
Pull locally and run `npm run serve`
  * _Note: I did test the scrolling on several screen sizes and mobile preview, and in multiple browsers, but would be good if you could test in multiple window sizes, too, and in Safari._

Will also need to be tested on beta once merged

### CODE REVIEW

File: src/assets/text/droughtAnnotations_mobile.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ export default {
       {
         id: '1980s_2',
         date: '1990-02-15',
-        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering the largest fire-fighting effort in the U.S. at that time.',
+        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering a large fire-fighting effort.',
```
Comment (aaarcher-usgs) [inline src/assets/text/droughtAnnotations_mobile.js:109]:
```suggestion
        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering the largest wildland fire-fighting effort in the U.S. up to that time.',
```

Comment (aaarcher-usgs) [reply src/assets/text/droughtAnnotations_mobile.js:109]: ^ that's what Meredith signed off on

**Review by aaarcher-usgs — APPROVED** [review]
RC: Change 1980s description on mobile and desktop to Meredith's approved version:

`triggering the largest wildland fire-fighting effort in the U.S. up to that time.`

Scroll button works to get to the first narration per drought (on desktop here in screenshot, and also on mobile -no screenshot):

image

Landing looks good on "small" laptop

image


Padding and everything looks good on mocked SE:

image

image

File: src/assets/text/droughtNarrations_desktop.js [hunk 2]
```diff
@@ -97,7 +97,7 @@ export default {
         title: '1980s Drought (1987 - 1992)',
         start_date: '1990-10-31',
         end_date: '1994-10-31',
-        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering the largest fire-fighting effort in the U.S. at that time. ',
+        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering a large fire-fighting effort.',
```
Comment (aaarcher-usgs) [inline src/assets/text/droughtNarrations_desktop.js:100]:
```suggestion
        text: 'In the summer of 1988, streamflow in the Mississippi River was so low that barges could not go up and down the lower section of the river. That same summer, wildfires burned 36% of Yellowstone National Park, triggering the largest wildland fire-fighting effort in the U.S. up to that time.',
```

**Comment by aaarcher-usgs** [comment]
Once merged, I'll push to beta for thorough mobile testing.
